config/routes.rb
Rails.application.routes.draw do

  put 'users/downgrade' => 'users#downgrade'

  resources :wikis

  resources :charges, only: [:new, :create]

  devise_for :users

  resources :collaborators, only: [:create, :destroy]

  root 'welcome#index'

end

app/models/collaborator.rb
class Collaborator < ActiveRecord::Base
  belongs_to :user
  belongs_to :wiki

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  has_many :wikis
  has_many :collaborators
  has_many :collaborations, through: :collaborators, source: :wiki
  before_save { self.role ||= :standard }

  enum role: [:standard, :premium, :admin]


end

app/models/wiki.rb
class Wiki < ActiveRecord::Base
  belongs_to :user
  has_many :collaborators, dependent: :destroy

  validates :title, presence: true
  validates :body, presence: true
  validates :user, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!, except: [:index, :show]
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def configure_permitted_parameters
    added_attrs = [:username, :email, :password, :password_confirmation, :remember_me]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
  end
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  def new
    @stripe_btn_data = {
      key: "#{ Rails.configuration.stripe[:publishable_key] }",
      description: "Blocipedia Premium — #{current_user.username}",
      amount: @amount
    }
  end

  def create
    @amount = 1500

    customer = Stripe::Customer.create(
      email: current_user.email,
      card: params[:stripeToken]
    )

    charge = Stripe::Charge.create(
      customer: customer.id,
      amount: @amount,
      description: "Blocipedia Premium — #{current_user.email}",
      currency: 'usd'
    )

    current_user.update_attribute(:role, 'premium')

    flash[:notice] = "Thank you for your payment, #{current_user.email}!"
    redirect_to root_path(current_user)

    rescue Stripe::CardError => e
      flash[:alert] = e.message
      redirect_to new_charge_path
  end
end

app/controllers/collaborators_controller.rb
class CollaboratorsController < ApplicationController

before_action :authenticate_user!

  def create
    @wiki = Wiki.find(params[:wiki_id])
    @user = User.find_by(email: params[:user_email])
    collab_exists = Collaborator.where(wiki: @wiki, user: @user).any?
    @collaborator = Collaborator.find_or_create_by(wiki: @wiki, user: @user)

    if collab_exists
      flash[:alert] = "Collaborator already exists."
      redirect_to edit_wiki_path(@wiki) and return
    end

    if @collaborator.valid?
      flash[:notice] = "Collaborator added."
      redirect_to @wiki
    else
      flash[:error] = "There was an error adding the collaborator."
      redirect_to edit_wiki_path(@wiki)
    end
  end

  def destroy
    @wiki = Wiki.find(params[:wiki_id])
    @user = User.find_by(email: params[:user_email])
    @collaborator = Collaborator.find_by(wiki: @wiki, user: @user)

    if @collaborator.destroy
      flash[:notice] = "Collaborator removed."
      redirect_to @wiki
    else
      flash[:error] = "There was an error removing the collaborator."
      redirect_to edit_wiki_path
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def downgrade
    User.transaction do
      current_user.update_attribute(:role, 'standard')
      current_user.wikis.update_all(private: false)
    end
    flash[:notice] = "You have downgraded to Standard."
    redirect_to root_path(current_user)
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end
end

app/controllers/wikis_controller.rb
class WikisController < ApplicationController
  before_action :authenticate_user!, except: :show

  def index
    @wikis = policy_scope(Wiki)
  end

  def show
    @wiki = Wiki.find(params[:id])
  end

  def new
    @wiki = Wiki.new
  end

  def create
    @wiki = Wiki.new(wiki_params)
    @wiki.user = current_user

    if @wiki.save
      flash[:notice] = "Wiki was saved."
      redirect_to @wiki
    else
      flash.now[:alert] = "There was an error saving the wiki. Please try again."
      render :new
    end
  end

  def edit
    @wiki = Wiki.find(params[:id])
  end

  def update
    @wiki = Wiki.find(params[:id])
    @wiki.assign_attributes(wiki_params)

    if @wiki.save
      flash[:notice] = "Wiki was updated."
      redirect_to @wiki
    else
      flash.now[:alert] = "There was an error saving the wiki. Please try again."
      render :edit
    end
  end

  def destroy
    @wiki = Wiki.find(params[:id])

    if @wiki.destroy
      flash[:notice] = "\"#{@wiki.title}\" was deleted successfully."
      redirect_to wikis_path
    else
      flash.now[:alert] = "There was an error deleting the post."
      render :show
    end
  end

  private

  def wiki_params
    params.require(:wiki).permit(:title, :body, :private)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def markdown(text)
    renderer = Redcarpet::Render::HTML.new()
    markdown = Redcarpet::Markdown.new(renderer)

    markdown.render(text).html_safe
  end
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/collaborators_helper.rb
module CollaboratorsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/wikis_helper.rb
module WikisHelper
end

app/views/charges/new.html.erb
<div class="top-buffer">
  <h1>Upgrade to Premium</h1>
</div>
<%= form_tag charges_path do %>
  <h4>Click the button!</h4>
  <script class='stripe-button' src="https://checkout.stripe.com/checkout.js" data-key="<%= @stripe_btn_data[:key] %>"
  data-amount="<%= @stripe_btn_data[:amount] %>" data-description="<%= @stripe_btn_data[:description] %>" ></script>
  <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blocipedia</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <ul class="nav nav-tabs">
      <li><%= link_to "Blocipedia", root_path %></li>

      <div class="col-md-6 offset-md-6">
        <% if user_signed_in? %>
          Signed in as: <strong><%= current_user.username %></strong> |
          <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> -
          <%= link_to "Sign Out", destroy_user_session_path, method: :delete, :class => 'navbar-link' %>
        <% end %>
      </div>
    </ul>

    <% if flash[:notice] %>
      <div class="alert alert-success">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:notice] %>
      </div>
    <%elsif flash[:alert] %>
      <div class="alert alert-warning">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:alert] %>
      </div>
    <% end %>

    <%= yield %>

  </div>
</body>
</html>

app/views/welcome/index.html.erb
<div class="container">
  <div class="jumbotron">
    <h1>Blocipedia</h1>
    <p>the world's leading source of useful knowledge</p>

    <p>
      <% if current_user %>
        <%= link_to "View All Wikis", wikis_path, class: 'btn btn-info' %>
        <%= link_to "Create Wiki", new_wiki_path, class: 'btn btn-success' %>
      <% else %>
        <%= link_to "Sign In", new_user_session_path %> or
        <%= link_to "Sign Up", new_user_registration_path, class: 'btn btn-primary' %> today!
      <% end %>
    </p>
  </div>
</div>

app/views/wikis/edit.html.erb
<h1>Edit Wiki</h1>

<div class="row">
  <div class="col-md-4">
    <p>Edit a wiki here.</p>
  </div>
  <div class="col-md-8">
    <%= form_for @wiki do |f| %>
      <div class="form-group">
        <%= f.label :title %>
        <%= f.text_field :title, class: 'form-control', placeholder: "Enter wiki title" %>
      </div>
      <div class="form-group">
        <%= f.label :body %>
        <%= f.text_area :body, rows: 8, class: 'form-control', placeholder: "Enter wiki text" %>
      </div>
      <div class="form-group">
        <%= f.submit "Save", class: 'btn btn-success' %>
      </div>
      <% if current_user.admin? || (current_user.premium? && current_user.wikis.include?(@wiki)) %>
          <div class="form-group">
            <%= f.label :private, class: 'checkbox' do %>
              <%= f.check_box :private, checked: @wiki.private? %> Private
            <% end %>
          </div>
      <% end %>
    <% end %>
    <% if current_user.admin? || (current_user.premium? && current_user.wikis.include?(@wiki)) %>
      <%= form_tag(collaborators_path) do %>
          <div class="form-group">
            <%= label_tag "Add Collaborator" %>
            <%= text_field_tag :user_email, nil, class: 'form-control', placeholder: "Enter collaborator email" %>
          </div>
          <%= hidden_field_tag :wiki_id, @wiki.id %>
          <div class="form-group">
            <%= submit_tag "Add", class: 'btn btn-primary' %>
          </div>
      <% end %>
      <%= form_tag(collaborator_path, method: "delete") do %>
          <div class="form-group">
            <%= label_tag "Remove Collaborator" %>
            <%= text_field_tag :user_email, nil, class: 'form-control', placeholder: "Enter collaborator email" %>
          </div>
          <%= hidden_field_tag :wiki_id, @wiki.id %>
            <div class="form-group">
              <%= submit_tag "Remove", class: 'btn btn-danger' %>
            </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/wikis/index.html.erb
<h1>All Wikis</h1>
<div>
  <%= link_to "Create Wiki", new_wiki_path, class: 'btn btn-success' %>
</div>
<div class="row top-buffer">
  <div class="col-md-8">
    <% @wikis.each do |wiki| %>
      <div class="media">
        <div class="media-body">
          <h4 class="media-heading">
            <%= link_to wiki.title, wiki_path(wiki.id)%>
          </h4>
        </div>
      </div>
    <% end %>
  </div>

</div>

app/views/wikis/new.html.erb
<h1>New Wiki</h1>

<div class="row">
  <div class="col-md-4">
    <p>Let's learn together! Create a new wiki here.</p>
  </div>
  <div class="col-md-8">
    <%= form_for @wiki do |f| %>
      <div class="form-group">
        <%= f.label :title %>
        <%= f.text_field :title, class: 'form-control', placeholder: "Enter wiki title" %>
      </div>
      <div class="form-group">
        <%= f.label :body %>
        <%= f.text_area :body, rows: 8, class: 'form-control', placeholder: "Enter wiki text" %>
      </div>
      <div class="form-group">
        <%= f.submit "Save", class: 'btn btn-success' %>
      </div>
      <% if current_user.admin? || current_user.premium? %>
        <div class="form-group">
          <%= f.label :private, class: 'checkbox' do %>
            <%= f.check_box :private %> Private
          <% end %>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/wikis/show.html.erb
<div class="container top-buffer">
  <%= link_to "View All Wikis", wikis_path, class: 'btn btn-info' %>
  <h1 class="top-buffer">
    <%= @wiki.title %>
  </h1>
  <% if @wiki.private == true %>
    <div class="text-warning">
      Private
    </div>
  <% end %> <br>
  <div class="media">
    <div class="media-body">
      <div class="media-heading text-primary">Creator:</div>
      <h4><%= @wiki.user.username %></h4>
      </div>
    <div class="media-body">
      <div class="media-heading text-primary">Collaborators:</div>
      <h4>
        <% collab_list = "" %>
        <% @wiki.collaborators.each do |collab|%>
          <% collab_list << (collab.user.username + ", ")%>
        <% end %>
        <%= collab_list.chomp(", ") %>
      </h4>
    </div>
  </div>
  <div class="top-buffer">
    <%= link_to "Edit", edit_wiki_path(@wiki), class: 'btn btn-success' %>
    <% if policy(@wiki).destroy? %>
      <%= link_to "Delete", @wiki, method: :delete, class: 'btn btn-danger', data: {confirm: "Are you sure you want to delete this wiki?"} %>
    <% end %>
  </div>
  <div class="row">
    <div class="col-md-8">
      <p><%= markdown(@wiki.body) %></p>
    </div>
  </div>
</div>